version: "3"

volumes:
  kong_data: {}
  konga_data: {}

networks:
  kong-net:
    external: false

services:
  # web-client:
  #   container_name: web-client
  #   image: web-client:latest
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - kong-net

  http-test:
    container_name: http-test
    image: http-test:latest
    ports:
      - "8181:80"
    networks:
      - kong-net

  grpc-test:
    container_name: grpc-test
    image: grpc-test:latest
    ports:
      - "8180:80"
    networks:
      - kong-net

  # grpcui:
  #   image: wongnai/grpcui:master
  #   container_name: grpcui
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - GRPCUI_SERVER=grpc-test:80
  #   depends_on:
  #     - grpc-test
  #   networks:
  #     - kong-net

  kong-database:
    container_name: kong-database
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "kong"
      POSTGRES_DB: "kong"
      POSTGRES_PASSWORD: "kongpass"
    networks:
      - kong-net
    restart: on-failure
    volumes:
      - kong_data:/var/lib/postgresql/data

  kong-migrations:
    container_name: kong-migrations
    image: kong:3.3.1-ubuntu
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_PASSWORD: "kongpass"
      KONG_PASSWORD: "test"
    networks:
      - kong-net
    restart: on-failure

  kong:
    container_name: kong
    # image: kong:3.3.1-ubuntu
    build:
      context: ./kong
      dockerfile: Dockerfile
    depends_on:
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 2s
      retries: 15
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kongpass"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      # KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_PROXY_LISTEN: "0.0.0.0:9000 http2, 0.0.0.0:9443 http2 ssl, 0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_PLUGINS: "grpc-gateway, kong-jwt2header, oidc"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      - kong-net
    restart: on-failure:5
    volumes:
      - ./GrpcTest/Protos:/var/lib/grpc/protos:ro
      - ./googleapis/google:/usr/local/opt/protobuf/include/google:ro
      - ./kong/kong-oidc:/usr/local/share/lua/5.1/kong/plugins/oidc

  # konga:
  #   image: pantsel/konga
  #   ports:
  #     - 1337:1337
  #   links:
  #     - kong:kong
  #   container_name: konga
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #     - kong-net
